package vista;

// EJEMPLO PARA ADSI
// DESARROLLADO POR ALVARO CÉSPEDES ROMERO
//import com.mysql.jdbc.Connection;
import controlador.ConexionMysql;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alvaro
 */
public class ActualizarPacientes extends javax.swing.JInternalFrame {

public String comandosql="Select * from Pacientes";
DefaultTableModel modeloejemplo; // Para configurar la tabla que se creo
 String NombresColumnas[]= new String[] {"CEDULA PACIENTE","NOMBRE PACIENTE","APELLIDO PACIENTE"};
//  String NombresColumnas[]= new String[] {"ID","NOMBRES","APELLIDOS","ESTADO"};
 
    public ActualizarPacientes() throws SQLException {
  
     modeloejemplo= new DefaultTableModel(null,NombresColumnas);
        initComponents();
     //llenarTabla();
     MostrarInformacion();
            }
  

    /**
     * Creates new form AgregarPacientes
     */
public void limpiarTabla()
{ int i,j=0,nfilas;
  nfilas=modeloejemplo.getRowCount();
  System.out.println("el numero de filas detectadas es" + nfilas);
  for(i=0;i<nfilas;i++)
  { modeloejemplo.removeRow(j); // borra la primera fila y despues de cada borrado
    System.out.println("vamos en el borrado "+i); // la primera fila cambia y sigue hasta 
  }      // borrar todas las filas de la tabla
    
        nfilas=modeloejemplo.getRowCount();
        etiNumFilas.setText("Hay "+nfilas+" registros en la tabla");    
}        

public void MostrarInformacion()
{
    
    int nFilas=0;
//    Cajon.setText("");
try {
         ConexionMysql ConectBD=new ConexionMysql();
         Statement sentencia; // st
         ResultSet resultado; //rs 
         Object nuevafila[]= new Object[4]; // 4 por que son 4 las columnas que tiene la tabla.
         
         ConectBD.IniciarConexion();
         Connection conn=ConectBD.getMyConnection();
         sentencia= conn.createStatement();
         
        // JOptionPane.showMessageDialog(null,"La consulta sera"+comandosql);
         resultado = sentencia.executeQuery(comandosql);
         ResultSetMetaData meta = resultado.getMetaData();
         int columnas = meta.getColumnCount();  //Mientras haya registros 
         System.out.println("aqui vamos...");
         
         while (resultado.next()) 
         {  System.out.println("estoy dentro del while");
           /*
            nuevafila[0]=resultado.getObject(1);
            nuevafila[1]=resultado.getObject(2);
            nuevafila[2]=resultado.getObject(3);
            nuevafila[3]=resultado.getObject(4); */
            for (int i = 0; i < columnas; i++) 
                {nuevafila[i]=resultado.getObject(i+1);
                
                }        
                
                modeloejemplo.addRow(nuevafila);
                System.out.println("fin del for");
                 
         }
         ConectBD.Cerrar();
        nFilas=modeloejemplo.getRowCount();
        etiNumFilas.setText("Hay "+nFilas+" registros en la tabla");
 //        JOptionPane.showMessageDialog(null,"La consulta fue realizada");
      } catch (SQLException ex) {
          Logger.getLogger(AgregarPacientes.class.getName()).log(Level.SEVERE, null, ex);
      }

}

 



   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrdenId = new javax.swing.JButton();
        btnOrdenNombre = new javax.swing.JButton();
        btnOrdenApellido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etiNumFilas = new javax.swing.JLabel();
        etiPaciente = new javax.swing.JLabel();
        cajaId = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        cajaApellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cajaFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("ACTUALIZAR PACIENTES");

        btnOrdenId.setText("POR ID");
        btnOrdenId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenIdActionPerformed(evt);
            }
        });

        btnOrdenNombre.setText("POR NOMBRE");
        btnOrdenNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenNombreActionPerformed(evt);
            }
        });

        btnOrdenApellido.setText("POR APELLIDO");
        btnOrdenApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenApellidoActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(102, 204, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 102));
        jTable1.setModel(modeloejemplo);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        etiNumFilas.setText("jLabel1");

        etiPaciente.setText("A CONTINUACION EDITE LAS CAJAS Y ACTUALICE LOS DATOS");

        jButton1.setText("ACTUALIZAR DATOS");

        jLabel1.setText("TEXTO A FILTRAR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajaId)
                                    .addComponent(cajaNombre)
                                    .addComponent(cajaApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cajaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOrdenId)
                                .addGap(102, 102, 102)
                                .addComponent(btnOrdenNombre)
                                .addGap(92, 92, 92)
                                .addComponent(btnOrdenApellido))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiNumFilas)
                            .addComponent(etiPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenId)
                    .addComponent(btnOrdenNombre)
                    .addComponent(btnOrdenApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiNumFilas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cajaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cajaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenNombreActionPerformed
        comandosql="Select * from Pacientes order by nombrePaciente";
     //   modeloejemplo.
     limpiarTabla();   
     MostrarInformacion();
    }//GEN-LAST:event_btnOrdenNombreActionPerformed

    private void btnOrdenIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenIdActionPerformed
       comandosql="Select * from Pacientes order by idPaciente";
       limpiarTabla(); 
       MostrarInformacion();
    }//GEN-LAST:event_btnOrdenIdActionPerformed

    private void btnOrdenApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenApellidoActionPerformed
        comandosql="Select * from Pacientes order by apellidoPaciente";
        limpiarTabla();
        MostrarInformacion();
    }//GEN-LAST:event_btnOrdenApellidoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int filaElegida;
        System.out.println("La fila seleccionada es :"+jTable1.getSelectedRow());
        // la linea de arriba, traera el numero de la fila donde se dio clic
        // se empieza a contar a partir de cero
        System.out.println("El valor obtenido es :"+  modeloejemplo.getValueAt(jTable1.getSelectedRow(),0));
        cajaId.setText(""+modeloejemplo.getValueAt(jTable1.getSelectedRow(),0));
        // En este caso, se pone cero, para que traiga el contenido de esa fila, con la primera columna
        // donde por lo general va la llave primaria, el idpaciente en este caso.
        // Aprendiz: Ya una vez se obtiene el idpaciente, se pueden hacer una consulta, guardar en unas cajas de texto
        // agregar un boton actualizar, y ejecutar un procedurede update
        // NOTA:
        // En este ejemplo, las cajas y el boton, son una ilustracion, pero hacerlo es facil, es hacer practicamente
        //lo mismo que una insercion. Eso ya depende de los RF y los RNF de cada proyecto.
        // La actualizacion, debera incluir que si se permite cambiar el id, este no se repita...
        // Al finalizar la actualizacion, se debera refrescar la tabla, para que muestre la informacion con cambios.
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdenApellido;
    private javax.swing.JButton btnOrdenId;
    private javax.swing.JButton btnOrdenNombre;
    private javax.swing.JTextField cajaApellido;
    private javax.swing.JTextField cajaFiltro;
    private javax.swing.JTextField cajaId;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel etiNumFilas;
    private javax.swing.JLabel etiPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


}
