package vista;

// EJEMPLO PARA ADSI
//import com.mysql.jdbc.Connection;
import controlador.ConexionMysql;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alvaro
 */
public class MostrarDoctores extends javax.swing.JInternalFrame {

public String comandosql="Select * from Doctores";
public String filtroEstado="ACTIVO";
DefaultTableModel modeloejemplo; // Para configurar la tabla que se creo
 String NombresColumnas[]= new String[] {"ID DOCTOR","NOMBRE DOCTOR","APELLIDO DOCTOR","ESTADO DOCTOR"};
//  String NombresColumnas[]= new String[] {"ID","NOMBRES","APELLIDOS","ESTADO"};
 
    public MostrarDoctores() throws SQLException {
  
     modeloejemplo= new DefaultTableModel(null,NombresColumnas);
        initComponents();
     //llenarTabla();
     MostrarInformacion();
            }
  

    /**
     * Creates new form AgregarPacientes
     */
public void limpiarTabla()
{ int i,j=0,nfilas;
  nfilas=modeloejemplo.getRowCount();
  System.out.println("el numero de filas detectadas es" + nfilas);
  for(i=0;i<nfilas;i++)
  { modeloejemplo.removeRow(j); // borra la primera fila y despues de cada borrado
    System.out.println("vamos en el borrado "+i); // la primera fila cambia y sigue hasta 
  }      // borrar todas las filas de la tabla
    
        nfilas=modeloejemplo.getRowCount();
        etiNumFilas.setText("Hay "+nfilas+" registros en la tabla");    
}        

public void MostrarInformacion()
{
    
    int nFilas=0;
//    Cajon.setText("");
try {
         ConexionMysql ConectBD=new ConexionMysql();
         Statement sentencia; // st
         ResultSet resultado; //rs 
         Object nuevafila[]= new Object[4]; // 4 por que son 4 las columnas que tiene la tabla.
         
         ConectBD.IniciarConexion();
         Connection conn=ConectBD.getMyConnection();
         sentencia= conn.createStatement();
         
        // JOptionPane.showMessageDialog(null,"La consulta sera"+comandosql);
         System.out.println("El comando a ejecutar sera: " + comandosql);
         resultado = sentencia.executeQuery(comandosql);
         ResultSetMetaData meta = resultado.getMetaData();
         int columnas = meta.getColumnCount();  //Mientras haya registros 

         
         while (resultado.next()) 
         { 
            for (int i = 0; i < columnas; i++) 
                {nuevafila[i]=resultado.getObject(i+1);
                
                }        
                
                modeloejemplo.addRow(nuevafila);
                System.out.println("fin del for");
                 
         }
         ConectBD.Cerrar();
        nFilas=modeloejemplo.getRowCount();
        etiNumFilas.setText("Hay "+nFilas+" registros en la tabla");
 //        JOptionPane.showMessageDialog(null,"La consulta fue realizada");
      } catch (SQLException ex) {
          Logger.getLogger(AgregarPacientes.class.getName()).log(Level.SEVERE, null, ex);
      }

}

 



   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrdenId = new javax.swing.JButton();
        btnOrdenNombre = new javax.swing.JButton();
        btnOrdenApellido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_selector_estado = new javax.swing.JToggleButton();
        etiNumFilas = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("MOSTRAR DOCTORES");

        btnOrdenId.setText("POR ID");
        btnOrdenId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenIdActionPerformed(evt);
            }
        });

        btnOrdenNombre.setText("POR NOMBRE");
        btnOrdenNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenNombreActionPerformed(evt);
            }
        });

        btnOrdenApellido.setText("POR APELLIDO");
        btnOrdenApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenApellidoActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(102, 204, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 102));
        jTable1.setModel(modeloejemplo);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("LIMPIAR TABLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_selector_estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono_filtro.png"))); // NOI18N
        btn_selector_estado.setSelected(true);
        btn_selector_estado.setText("ACTIVO / INACTIVO");
        btn_selector_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selector_estadoActionPerformed(evt);
            }
        });

        etiNumFilas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiNumFilas)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnOrdenId)
                            .addGap(31, 31, 31)
                            .addComponent(btnOrdenNombre)
                            .addGap(26, 26, 26)
                            .addComponent(btnOrdenApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_selector_estado))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiNumFilas)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenId)
                    .addComponent(btnOrdenNombre)
                    .addComponent(btnOrdenApellido)
                    .addComponent(btn_selector_estado))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );

        getAccessibleContext().setAccessibleName("MOSTRAR DOCTORES");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenNombreActionPerformed
        comandosql="Select * from doctores where estadoDoctor='"+filtroEstado+"' order by nombreDoctor";
     //   modeloejemplo.
     limpiarTabla();   
     MostrarInformacion();
    }//GEN-LAST:event_btnOrdenNombreActionPerformed

    private void btnOrdenIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenIdActionPerformed
       comandosql="Select * from doctores where estadoDoctor='"+filtroEstado+"' order by idDoctor";
       limpiarTabla(); 
       MostrarInformacion();
    }//GEN-LAST:event_btnOrdenIdActionPerformed

    private void btnOrdenApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenApellidoActionPerformed
        comandosql="Select * from doctores where estadoDoctor='"+filtroEstado+"' order by apellidoDoctor";
        limpiarTabla();
        MostrarInformacion();
    }//GEN-LAST:event_btnOrdenApellidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int filaElegida;
        //modeloejemplo.getValueAt(ERROR, WIDTH)
      //  filaElegida=modeloejemplo   
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_selector_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selector_estadoActionPerformed
        // TODO add your handling code here:
      if(btn_selector_estado.isSelected()==true)
      { filtroEstado="INACTIVO";
        btn_selector_estado.setText("VER SOLO INACTIVOS");
      }
      if(btn_selector_estado.isSelected()==false)
      { filtroEstado="ACTIVO";
        btn_selector_estado.setText("VER SOLO ACTIVOS");
      }
      limpiarTabla();
      MostrarInformacion();
    }//GEN-LAST:event_btn_selector_estadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdenApellido;
    private javax.swing.JButton btnOrdenId;
    private javax.swing.JButton btnOrdenNombre;
    private javax.swing.JToggleButton btn_selector_estado;
    private javax.swing.JLabel etiNumFilas;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


}
