package vista;

// EJEMPLO PARA ADSI
//import com.mysql.jdbc.Connection;
import controlador.ConexionMysql; // Se esta incluyendo la clase, de ese paquete
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alvaro
 */
public class MostrarPacientes1 extends javax.swing.JInternalFrame {

public String comandosql="Select * from Pacientes";
    /**
     * Creates new form AgregarPacientes
     */


public void MostrarInformacion()
{
    Cajon.setText("");
try {
         ConexionMysql Puente=new ConexionMysql();
         Statement sentencia; // st
         ResultSet resultado; //rs 
         
         Puente.IniciarConexion();
         Connection conn=Puente.getMyConnection();
         sentencia= conn.createStatement();
         
        // JOptionPane.showMessageDialog(null,"La consulta sera"+comandosql);
         resultado = sentencia.executeQuery(comandosql);
         ResultSetMetaData meta = resultado.getMetaData();
         int columnas = meta.getColumnCount();  //Mientras haya registros 
         
         while (resultado.next()) 
         {
                for (int i = 1; i <= columnas; i++) 
                { //Mostrar el dato del campo i
                  Cajon.append(resultado.getString(i)+ "\t");
                } Cajon.append("\n");
         }
         Puente.Cerrar();

      //  JOptionPane.showMessageDialog(null,"La consulta fue realizada correctamente");
      } catch (SQLException ex) {
          //Logger.getLogger(AgregarPacientes.class.getName()).log(Level.SEVERE, null, ex);
          JOptionPane.showMessageDialog(null, "Se presento un error en la consulta de BD");
          
      }

}

 

    public MostrarPacientes1() throws SQLException {
     initComponents();
     MostrarInformacion();
            }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Cajon = new javax.swing.JTextArea();
        btnOrdenId = new javax.swing.JButton();
        btnOrdenNombre = new javax.swing.JButton();
        btnOrdenApellido = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setTitle("MOSTRAR PACIENTES");

        Cajon.setColumns(20);
        Cajon.setRows(5);
        jScrollPane1.setViewportView(Cajon);

        btnOrdenId.setText("POR ID");
        btnOrdenId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenIdActionPerformed(evt);
            }
        });

        btnOrdenNombre.setText("POR NOMBRE");
        btnOrdenNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenNombreActionPerformed(evt);
            }
        });

        btnOrdenApellido.setText("POR APELLIDO");
        btnOrdenApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenApellidoActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnOrdenId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrdenNombre)
                        .addGap(32, 32, 32)
                        .addComponent(btnOrdenApellido))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenId)
                    .addComponent(btnOrdenNombre)
                    .addComponent(btnOrdenApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenNombreActionPerformed
        comandosql="Select * from Pacientes order by nombrePaciente";
        MostrarInformacion();
    }//GEN-LAST:event_btnOrdenNombreActionPerformed

    private void btnOrdenIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenIdActionPerformed
       comandosql="Select * from Pacientes order by idPaciente";
        MostrarInformacion();
    }//GEN-LAST:event_btnOrdenIdActionPerformed

    private void btnOrdenApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenApellidoActionPerformed
        comandosql="Select * from Pacientes order by apellidoPaciente";
        MostrarInformacion();
    }//GEN-LAST:event_btnOrdenApellidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cajon;
    private javax.swing.JButton btnOrdenApellido;
    private javax.swing.JButton btnOrdenId;
    private javax.swing.JButton btnOrdenNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
